Repository dagster-io/dagster, pull requests merged in 2021-11, with the labels that each got.

#5388 hacker news job improvements
  examples/hacker_news/hacker_news/jobs/dbt_metrics.py
  examples/hacker_news/hacker_news/jobs/hacker_news_api_download.py
  examples/hacker_news/hacker_news/jobs/story_recommender.py
  examples/hacker_news/hacker_news/legacy/pipelines/dbt_pipeline.py
  examples/hacker_news/hacker_news/legacy/pipelines/download_pipeline.py
  examples/hacker_news/hacker_news/legacy/pipelines/story_recommender.py
  examples/hacker_news/hacker_news/ops/comment_stories.py
  examples/hacker_news/hacker_news/ops/download_items.py
  examples/hacker_news/hacker_news/ops/id_range_for_time.py
  examples/hacker_news/hacker_news/ops/user_story_matrix.py
  examples/hacker_news/hacker_news/repo.py
  examples/hacker_news/hacker_news/resources/__init__.py
  examples/hacker_news/hacker_news/resources/common_bucket_s3_pickle_io_manager.py
  examples/hacker_news/hacker_news/resources/fixed_s3_pickle_io_manager.py
  examples/hacker_news/hacker_news/resources/parquet_io_manager.py
  examples/hacker_news/hacker_news/resources/partition_bounds.py
  examples/hacker_news/hacker_news/resources/s3_notebook_io_manager.py
  examples/hacker_news/hacker_news/resources/snowflake_io_manager.py
  examples/hacker_news/hacker_news_dbt/config/profiles.yml
  examples/hacker_news/hacker_news_tests/test_jobs/test_hacker_news_api_download.py
  examples/hacker_news/hacker_news_tests/test_legacy.py
  examples/hacker_news/hacker_news_tests/test_ops/test_comment_stories.py
  examples/hacker_news/hacker_news_tests/test_ops/test_id_range_for_time.py
  examples/hacker_news/hacker_news_tests/test_ops/test_user_story_matrix.py
  examples/hacker_news/hacker_news_tests/test_resources/test_parquet_io_manager.py
  examples/hacker_news/hacker_news_tests/test_resources/test_snowflake_io_manager.py
  examples/hacker_news_assets/hacker_news_assets/assets/download_items.py
Labels: demo pipelines

#5302 remove hacker news legacy circular sensor
  examples/hacker_news/hacker_news/legacy/repo.py
Labels: demo pipelines

#5505 pipeline instead of job in slack_on_run_failure_sensor
  python_modules/libraries/dagster-slack/dagster_slack/sensors.py
Labels: graph-job-op

#5483 mostly cosmetic improvements to hacker news jobs
  examples/hacker_news/hacker_news/jobs/dbt_metrics.py
  examples/hacker_news/hacker_news/jobs/hacker_news_api_download.py
  examples/hacker_news/hacker_news/jobs/story_recommender.py
  examples/hacker_news/hacker_news/legacy/pipelines/dbt_pipeline.py
  examples/hacker_news/hacker_news/legacy/pipelines/download_pipeline.py
  examples/hacker_news/hacker_news/legacy/pipelines/story_recommender.py
  examples/hacker_news/hacker_news/resources/snowflake_io_manager.py
  examples/hacker_news/hacker_news_tests/test_resources/test_snowflake_io_manager.py
Labels: demo pipelines

#5529 DaskClusterTypes refactoring
  python_modules/libraries/dagster-dask/dagster_dask/resources.py
Labels: platform

#5556 executor_def argument to build_assets_job
  python_modules/dagster/dagster/core/asset_defs/assets_job.py
Labels: asset-defs

#5516 move schedule and ScheduleDefinition docstring to job
  python_modules/dagster/dagster/core/definitions/decorators/schedule.py
  python_modules/dagster/dagster/core/definitions/schedule.py
Labels: graph-job-op

#5684 remove parquet pointer
  examples/hacker_news/hacker_news/resources/parquet_pointer.py
Labels: demo pipelines

#5823 unbreak foreign assets in dagit
  python_modules/dagster/dagster/core/host_representation/external_data.py
Labels: asset-defs

#5742 Big honkin asset graph
  python_modules/dagster-test/dagster_test/graph_job_op_toys/big_honkin_asset_graph.py
Labels: asset-defs
