Repository dagster-io/dagster, pull requests merged in 2022-09, with the labels that each got.

#9528 [docs] - Update diagram images in Versioning + memoization guide
  docs/content/guides/dagster/memoization.mdx
  docs/next/public/images/guides/versioning_memoization/op-version-computation.png
  docs/next/public/images/guides/versioning_memoization/resource-version-computation.png
Labels: documentation

#9629 [docs] - Add callout for SDA videos
  docs/content/concepts/assets/software-defined-assets.mdx
Labels: documentation

#9460 remove graph-backed asset note
  docs/content/concepts/assets/software-defined-assets.mdx
Labels: documentation

#9247 [docs] - Clean up Guides sidenav + category page
  docs/content/_navigation.json
  docs/content/guides.mdx
  docs/content/guides/best-practices.mdx
  docs/content/guides/experimental-features.mdx
  docs/content/guides/general.mdx
Labels: documentation

#9643 [docs] - Dagster Cloud full deployment docs
  docs/content/_navigation.json
  docs/content/dagster-cloud/developing-testing/deployment-settings-reference.mdx
  docs/content/dagster-cloud/developing-testing/managing-deployments.mdx
  docs/next/public/images/dagster-cloud/developing-testing/deployments/deployment-settings.png
  docs/next/public/images/dagster-cloud/developing-testing/deployments/deployment-switcher.png
Labels: cloud-documentation

#9695 [docs] - Graph-backed asset subsetting docs
  docs/content/_navigation.json
  docs/content/concepts/assets/graph-backed-assets.mdx
  docs/content/concepts/assets/software-defined-assets.mdx
  docs/content/concepts/ops-jobs-graphs/graphs.mdx
  docs/next/public/images/concepts/assets/graph-backed-asset.png
  examples/docs_snippets/docs_snippets/concepts/assets/subset_graph_backed_asset.py
  examples/docs_snippets/docs_snippets/concepts/assets/subset_graph_backed_asset_unexpected_materializations.py
  examples/docs_snippets/docs_snippets_tests/concepts_tests/assets_tests/test_graph_backed_asset_subset.py
Labels: documentation

#9732 modernize dynamic_tests
  python_modules/dagster/dagster_tests/execution_tests/dynamic_tests/test_dsl.py
  python_modules/dagster/dagster_tests/execution_tests/dynamic_tests/test_dynamic_execution.py
  python_modules/dagster/dagster_tests/execution_tests/dynamic_tests/test_dynamic_output.py
  python_modules/dagster/dagster_tests/execution_tests/dynamic_tests/test_not_allowed.py
  python_modules/dagster/dagster_tests/execution_tests/dynamic_tests/test_reexecute.py
Labels: fixit-week

#8564 k8s executor pass args via env var
  python_modules/dagster/dagster/_cli/api.py
  python_modules/dagster/dagster/_grpc/types.py
  python_modules/libraries/dagster-k8s/dagster_k8s/executor.py
  python_modules/libraries/dagster-k8s/dagster_k8s/job.py
Labels: fixit-week

#9730 [docs] - Fix IS_BRANCH_DEPLOYMENT docs examples
  docs/content/guides/dagster/branch_deployments.mdx
  examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/branch_deployments/repository_v1.py
  examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/branch_deployments/repository_v2.py
  examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/branch_deployments/repository_v3.py
Labels: cloud-documentation

#9768 [fixit] Add library versions to docs
  docs/next/components/Link.tsx
  docs/next/components/VersionDropdown.tsx
  docs/next/scripts/mdx-transform.ts
  docs/next/util/codeBlockTransformer.ts
Labels: documentation

#9754 [docs] - simplify multi-asset sensor examples and fix formatting
  docs/content/concepts/partitions-schedules-sensors/sensors.mdx
  examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/sensors/sensors.py
  examples/docs_snippets/docs_snippets_tests/concepts_tests/partitions_schedules_sensors_tests/test_sensors.py
Labels: documentation
